---
title: "R Notebook"
output: html_notebook
---

```{r}
library(fmatrix)
library(phylodyn)
library("phangorn")
library("mvtnorm")
library("ape")

root <- rprojroot::has_file("DESCRIPTION")
setwd(root$find_file("vignettes/beast_compare/"))

# source("simulation_dna_for_Beast.R")
```

```{r}
dataname <- "temp2"

true_tree <- readRDS(paste0(dataname, ".RDS"))
true_Fmat <- gen_Fmat(true_tree)
```

```{r}
mcc_tree <- ape::read.nexus(paste0(dataname, ".mcc"))
mcc_Fmat <- gen_Fmat(mcc_tree)
is.Fmat(mcc_Fmat)

# plot.new()
# plotF(mcc_Fmat)
```

```{r}
schedule <- "lin"
load(paste(dataname, schedule, "schedule.RData", sep = "_"))
lin_min.config <- track.config[which.min(track.energy.config), ]

schedule <- "log"
load(paste(dataname, schedule, "schedule.RData", sep = "_"))
log_min.config <- track.config[which.min(track.energy.config), ]

schedule <- "exp"
load(paste(dataname, schedule, "schedule.RData", sep = "_"))
exp_min.config <- track.config[which.min(track.energy.config), ]
```

```{r}
par(mfrow = c(2,3))

exp_min.config %>%
  tree_from_matching %>% gen_Fmat %>% plotF; title('exp')
lin_min.config %>%
  tree_from_matching %>% gen_Fmat %>% plotF; title('lin')
log_min.config %>%
  tree_from_matching %>% gen_Fmat %>% plotF; title('log')

true_Fmat %>% plotF; title('true')
mcc_Fmat %>% plotF; title('mcc-TreeAnnotator')
mcc_Fmat2 %>% plotF; title('mcc-phangorn')
```

```{r}
energy(matching(mcc_tree))
energy(lin_min.config)
energy(log_min.config)
energy(exp_min.config)

```

```{r}
## Question 0:  Is True Tree meaningful?
## Question 1:  Is the True Frechet Mean of the Posterior distribn close to the True Tree?
## Question 2:  Is our approximation of Frechet Mean close to True Frechet Mean?

## Question A:  Point estimate vs Credible sets
distance_Fmat(true_Fmat, mcc_Fmat, dist = "l2", scale = 1)
distance_Fmat(true_Fmat, exp_min.config %>%
                tree_from_matching %>% gen_Fmat, dist = "l2", scale = 1)
distance_Fmat(true_Fmat, log_min.config %>%
                tree_from_matching %>% gen_Fmat, dist = "l2", scale = 1)
distance_Fmat(true_Fmat, lin_min.config %>%
                tree_from_matching %>% gen_Fmat, dist = "l2", scale = 1)
```



```{r}
par(mfrow = c(1,3))
out <- lapply(Fmat_list, distance_Fmat, Fmat2 = gen_Fmat(treeP))
hist(unlist(out), main = NULL); title('distances to true')
out2 <- lapply(Fmat_list, distance_Fmat, Fmat2 = exp_min.config %>%
                 tree_from_matching %>% gen_Fmat)
hist(unlist(out2), main = NULL); title('distances to exp')
out_mcc <- lapply(Fmat_list, distance_Fmat, Fmat2 = gen_Fmat(mcc_tree))
hist(unlist(out_mcc), main = NULL); title('distances to mcc-TreeAnnotator')
```



```{r}
subtr.list <- ape::subtrees(treeP, wait=TRUE)
child.ntip <- data.frame(node.id=(1:Nnode(treeP))+n.tip,
                         n.tip=unlist(lapply(subtr.list, Ntip)))

subtr.list_mcc <- ape::subtrees(mcc_tree, wait=TRUE)
child.ntip <- data.frame(node.id=(1:Nnode(treeP))+n.tip,
                         n.tip=unlist(lapply(subtr.list, Ntip)))


```



```{r}
exp_lambda <- exp_min.config %>%
  tree_from_matching %>% gen_Fmat %>% colSums
lin_lambda <- lin_min.config %>%
  tree_from_matching %>% gen_Fmat %>% colSums
log_lambda <- log_min.config %>%
  tree_from_matching %>% gen_Fmat %>% colSums

true_lambda <- true_Fmat %>% colSums

mcc_lambda <- mcc_Fmat %>% colSums

rbind(exp_lambda, mcc_lambda, true_lambda) %>% View

(exp_lambda - true_lambda) %>% plot


lambda_list <- lapply(F.list9, colSums); length(unique(lambda_list))
dlambda_list <- lapply(D.list9, colSums); length(unique(dlambda_list))

lambda_list[which(lapply(lambda_list, ))]

which(duplicated(lambda_list))
```
