---
title: "Visualising F-matrix space"
output: html_document
---

```{r setup}
library(fmatrix)
library(phylodyn)
library(dplyr)

options(rgl.useNULL = TRUE) # Suppress the separate window.
library(rgl)
```

```{r}
singleevent <- function(all.times){
  ret <- apply(all.times, 1, function(u){
    !any(duplicated(u))
  })
  all.times[ret,]
}


alltrees <- function(Fmat, all.times){
  
  allfunction <- function(time){
    return(mytree_from_F(Fmat, coal.times = time))
  }
  
  ret <- apply(all.times, 1, allfunction)
  
  return(ret)
}


mydist <- function(tree.list){
  nrow <- length(tree.list)
  
  dmat <- matrix(nrow = nrow, ncol = nrow)
  for(i in 1:nrow){
    for(j in 1:i){
      dmat[i,j] <- dmat[j,i] <- 
        dist_pairwise(tree.list[[i]], tree.list[[j]], 
                      dist.method = "l2", weighted = TRUE)
    }
  }
  return(dmat)
}

mydist2 <- function(Fmat.list, Wmat.list){
  nrow <- length(Fmat.list)
  matrix_F <- fmatrix::matrix_list(Fmat.list)
  matrix_W <- fmatrix::matrix_list(Wmat.list)
  
  matrix_FW <- matrix_F * matrix_W
  
  return(dist(t(matrix_FW), method = "euclidean"))
}

alltrees_allF <- function(F.list, all.times){
  Fmat.list <- times.list <- trees.list <- index.list <- list()
  for(i in 1:length(F.list)){
    trees.list <- append(trees.list, alltrees(F.list[[i]], all.times))
    Fmat.list <- append(Fmat.list, rep(list(F.list[[i]]), nrow(all.times)))
    times.list <- append(times.list, plyr::alply(all.times, 1, function(u){rev(as.numeric(u))}))
    index.list <- append(index.list, rep(list(i), nrow(all.times)))
  }
  return(list(Fmat.list = Fmat.list,
              trees.list = trees.list,
              times.list = times.list,
              index.list = index.list))
}
```


```{r}
F.list <- F.list5

ncol(F.list[[1]])

breaks <- seq(0,1,by=.1)
all.times <- expand.grid(breaks, breaks, breaks, breaks)
all.times <- all.times[rowSums(all.times) <= 1, ]
all.times <- apply(all.times, 1, 
                   function(u){
                     c(u[1], 
                       u[1] + u[2], 
                       u[1] + u[2] + u[3],
                       u[1] + u[2] + u[3] + u[4])
                     }) %>% t
all.times <- data.frame(all.times)
all.times <- distinct(all.times)
all.times <- as.matrix(all.times)
all.times <- singleevent(all.times)
```


```{r}
ret <- alltrees_allF(F.list, all.times)

Fmat.list <- ret$Fmat.list
trees.list <- ret$trees.list
times.list <- ret$times.list
index.list <- ret$index.list
Wmat.list <- lapply(times.list, wt_from_times)

F_index <- unlist(index.list)
```


```{r}
# dmat <- mydist(temp, all.times)


dmat <- mydist2(Fmat.list, Wmat.list)
```




```{r}
cmd <- cmdscale(dmat, eig = TRUE, k = 3)

ratio <- sqrt(cmd$eig[1:3]/sum(cmd$eig))

plot3d(cmd$points[,1], cmd$points[,2], cmd$points[,3], col = F_index, aspect = ratio)

```


<!-- ```{r} -->
<!-- tsn <- Rtsne::Rtsne(dmat, dims = 3, is_distance = TRUE) -->
<!-- plot3d(tsn$Y[,1], tsn$Y[,2], tsn$Y[,3], col = F_index) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- F.list <- F.list6 -->

<!-- breaks <- seq(0,1,by=.1) -->
<!-- all.times_6 <- expand.grid(breaks, breaks, breaks, breaks, breaks) -->
<!-- all.times_6 <- all.times[rowSums(all.times_6) <= 1, ] -->
<!-- all.times_6 <- apply(all.times_6, 1,  -->
<!--                    function(u){ -->
<!--                      c(u[1],  -->
<!--                        u[1] + u[2],  -->
<!--                        u[1] + u[2] + u[3], -->
<!--                        u[1] + u[2] + u[3] + u[4],  -->
<!--                        u[1] + u[2] + u[3] + u[4] + u[5]) -->
<!--                      }) %>% t -->
<!-- all.times_6 <- data.frame(all.times_6) -->
<!-- all.times_6 <- distinct(all.times_6) -->
<!-- all.times_6 <- as.matrix(all.times_6) -->
<!-- all.times_6 <- singleevent(all.times_6) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- ret_6 <- alltrees_allF(F.list6, all.times_6) -->

<!-- Fmat.list_6 <- ret_6$Fmat.list -->
<!-- trees.list_6 <- ret_6$trees.list -->
<!-- times.list_6 <- ret_6$times.list -->
<!-- index.list_6 <- ret_6$index.list -->
<!-- Wmat.list_6 <- lapply(times.list_6, wt_from_times) -->

<!-- F_index_6 <- unlist(index.list_6) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # dmat <- mydist(temp, all.times) -->


<!-- dmat_6 <- mydist2(Fmat.list, Wmat.list) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- cmd_6 <- cmdscale(dmat_6, eig = TRUE, k = 3) -->

<!-- ratio_6 <- sqrt(cmd_6$eig[1:3]/sum(cmd_6$eig)) -->

<!-- plot3d(cmd_6$points[,1], cmd_6$points[,2], cmd_6$points[,3], col = F_index_6, aspect = ratio_6) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- tsn_6 <- Rtsne::Rtsne(dmat_6, dims = 3, is_distance = TRUE) -->
<!-- plot3d(tsn_6$Y[,1], tsn_6$Y[,2], tsn_6$Y[,3], col = F_index_6) -->
<!-- ``` -->
